update_tweets:
  cron: "0 * * * *"
  queue: tweet_update_queue
  class: TweetUpdater
  args:
  description:

classify_tweets_using_bayesian_classifier:
  cron: "*/5 * * * *"
  queue: bayesian_classification_update_queue
  class: BayesianClassificationUpdater
  args:
  description:
